name: gateway
requires:
- auth

memory: 0.25G
cpu: 0.25

routes:
  "/cluster": kubernaut.{{"dev" if env.K8S_NAMESPACE == "dev" else "kubernaut"}}.svc.cluster.local
  "/scout-canary": scout-canary.scout.svc.cluster.local
  "/scout": scout.scout.svc.cluster.local
